#Minecraft server GUI configuration. No server jar detected, leaving mock mode enabled.
#Fri Apr 03 22:11:38 EDT 2026
app.title=Minecraft Server Console
mock.mode=true
poll.heap.seconds=20
poll.players.seconds=30
poll.tps.seconds=30
server.command=java -Xms3G -Xmx6G -jar server.jar nogui
working.directory=.
